### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by luangjokaj** [postcss/gulp-postcss#117]
Since the last update from 6.4.0 to 7.0.0 the nesting seem to be broken.
For example this **doesn't output correctly**, the ul is missing the styling completely.

Any idea why? In version 6.4.0 there are no issues whatsoever with the same CSS.
```
header {
	background-color: var(--primary-color);
	position: fixed;
	left: 0;
	top: 0;
	height: 100vh;
	width: 200px;

	& .logo {
		width: 90%;
	}

	& nav {
		border: 1px solid yellow;

		& ul {
			list-style-type: none;
			color: var(--white);
			margin: 0;
			padding: 0;

			& li {
				display: block;
				font-size: 12px;
				text-align: center;
				border-bottom: 1px solid color(var(--secondary-color) a(20%));

				& a {
					color: var(--secondary-color);
					display: block;
					padding: 15px 0;
				}
			}
		}
	}
}
```

**Comment by michael-ciniawsky** [comment]
@luangjokaj `gulp-postcss >= 7.0.0` uses PostCSS 6 and if you use e.g `postcss-nested` you need to update it to `>= 2.x` (SASS) , in case you use `cssnext`, which includes `postcss-nesting` (CSSWG Spec) wait until https://github.com/MoOx/postcss-cssnext/issues/374 is resolved. The issue is unrelated to `gulp-postcss` itself or any other build middleware, as I got the same for `postcss-loader` a few times now 😛

**Comment by w0rm** [comment]
@luangjokaj `gulp-postcss` bumped the major version of PostCSS, so there may be incompatibilities with some plugins. Please check what plugins are broken, update them to the most recent versions, or open issues in the corresponding repositories, or use the previous version of `gulp-postcss` until all plugins are migrated.
