### ISSUE TITLE
Watch function is not working

### ISSUE THREAD

**Issue by mittalyashu** [postcss/gulp-postcss#131]
How to resolve this error?

![image](https://user-images.githubusercontent.com/29014463/27987894-61fb7d90-6433-11e7-8f99-8e1cc65954a9.png)

**Comment by mittalyashu** [comment]
Somehow I managed to fix the previous problem. But now, I am not able to automically  update the css file.

```
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('watch:sass', function () {
  return gulp.src('./sass/style.sass')
    .pipe(sass())
    .pipe(gulp.dest('./css'));
});
gulp.watch('./sass/style.sass'); 
```

**Comment by w0rm** [comment]
You probably need to use `.watch` instead of `.src`. Anyways, this is project is `gulp-postcss` plugin that you're not using, and it looks that you need help with using `gulp` in general, for this you may refer for the gulp api https://github.com/gulpjs/gulp/blob/master/docs/API.md or try to find some basic gulp tutorials.
