### ISSUE TITLE
PostCSS dependency messages are not respected

### ISSUE THREAD

**Issue by adamwathan** [postcss/gulp-postcss#173]
PostCSS plugins can use `result.messages` to send dependency messages to the build runner to let it know that when certain files change, the CSS file needs to be rebuilt:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/4323180/118032337-8e7b0e80-b335-11eb-8220-ec6f041d7203.png">

[Relevant documentation](https://github.com/postcss/postcss/blob/main/docs/writing-a-plugin.md)

`gulp-postcss` doesn't seem to check these messages, and as a result rebuilds aren't triggered when those dependencies change as they should be.

Reproduction here:

https://github.com/adamwathan/gulp-postcss-dependency-bug

This is the underlying reason for this bug reported to Tailwind CSS here:

https://github.com/tailwindlabs/tailwindcss/issues/4320

Thanks!

**Comment by w0rm** [comment]
Oh I see where this is coming from in the readme (cc @ai): 

> If your plugin load another file, you can use result to add message, that webpack/Gulp should add this file to a watching list (and rebuild CSS on file changes)

Gulp plugins transform files in the stream. Gulp is not a dependency tree builder, there is nowhere to report that PostCSS had to pull extra dependencies in order to compile a file from the stream. 

I guess all dependencies have to be listed in `gulp.watch` in order for the example to work:

```diff
gulp.task('watch', function () {
--  gulp.watch('./src/*.css', gulp.series['css'])
++  gulp.watch(['./src/*.css', './dependency.txt'], gulp.series['css'])
})
```

Either that, or you can run postcss cli from a gulp task.

**Comment by w0rm** [comment]
https://github.com/postcss/gulp-postcss/issues/172 was a similar issue
